let myEvents = JSON.parse(`{
    "myEvent": [
       {
         "id": "1",
         "name": "SHOW OFF. Austrian Fashion Design",
         "image": "img/events/showoff.JPG",
         "place": "MAK - Museum für angewandte Kunst",
         "address": "Stubenring 5",
         "district": "1010",
         "city": "Vienna",
         "Tel": "+43 1 711 36 0",
         "dateVon": "14. Februar 2020",
         "datebis": "12. Juli 2020",
         "timeEve": "20:00",
         "price": "10",
         "type": "Music & Stage Shows",
         "website": "www.mak.at"
         
       },
       {
         "id": "2",
         "name": "Alec Soth",
         "image": "img/events/alec.JPG",
         "place": "Kunst Haus Wien Museum Hundertwasser",
         "address": "Untere Weißgerberstraße 13",
         "district": "1030",
         "city": "Vienna",
         "Tel": "+43 1 712 04 91",
         "dateVon": "26. Februar 2020",
         "datebis": "16. August 2020",
         "timeEve": "20:00",
         "price": "10",
         "type": "Photography",
         "website": "www.kunsthauswien.com"

       },
       {
         "id": "3",
         "name": "Hundertwasser - Schiele",
         "image": "img/events/hunderwasser.JPG",
         "place": "Leopold Museum",
         "address": "Museumsplatz 1",
         "district": "1070",
         "city": "Vienna",
         "Tel": "+43 1 525 70 0",
         "dateVon": "21. Februar 2020",
         "datebis": "31. August 2020",
         "timeEve": "17:00",
         "price": "13",
         "type": "Art",
         "website": "www.leopoldmuseum.org"
       },
       {
         "id": "4",
         "name": "70 Jahre Filmpremiere Der dritte Mann",
         "image": "img/events/filmpremiere.JPG",
         "place": "Dritte Mann Museum",
         "address": "Pressgasse 25",
         "district": "1040",
         "city": "Vienna",
         "Tel": "+43 1 586 48 72",
         "dateVon": "11. Mai 2018",
         "datebis": "6. Jänner 2021",
         "timeEve": "17:00",
         "price": "13",
         "type": "Movie",
         "website": "www.thirdmanmuseum.com"
       },
       {
         "id": "5",
         "name": "Die frühe Radierung. Von Dürer bis Bruegel",
         "image": "img/events/radierung.JPG",
         "place": "Albertina",
         "address": "Albertinaplatz 1",
         "district": "1010",
         "city": "Vienna",
         "Tel": "+43 1 534 83 0",
         "dateVon": "12. Februar 2020",
         "datebis": "10. Mai 2020",
         "timeEve": "17:00",
         "price": "13",
         "type": "History",
         "website": "www.albertina.at"
       },
       {
         "id": "6",
         "name": "Design Lithuania. A House Full of Creativity",
         "image": "img/events/design.JPG",
         "place": "Designforum Wien im MuseumsQuartier",
         "address": "Museumsplatz 1, Hof 7",
         "district": "1070",
         "city": "Vienna",
         "Tel": "++43 1 524 49 490",
         "dateVon": "29. Jänner 2020",
         "datebis": "8. März 2020",
         "timeEve": "17:00",
         "price": "13",
         "type": "Design",
         "website": "www.designforum.at/"
       },{
         "id": "7",
         "name": "Wien 1900",
         "image": "img/events/modern.JPG",
         "place": "Leopold Museum",
         "address": "Museumsplatz 1",
         "district": "1070",
         "city": "Vienna",
         "Tel": "+43 1 525 70 0",
         "dateVon": "16. März 2019",
         "datebis": "25. August 2020",
         "timeEve": "17:00",
         "price": "13",
         "type": "Art",
         "website": "www.leopoldmuseum.org"
       },
       {
         "id": "8",
         "name": "Family Matters",
         "image": "img/events/family.JPG",
         "place": "Dom Museum Wien",
         "address": "Stephansplatz 6",
         "district": "1010",
         "city": "Vienna",
         "Tel": "+43 1 51 55 25 300",
         "dateVon": "14. Oktober 2019",
         "datebis": "30. August 2020",
         "timeEve": "17:00",
         "price": "20",
         "type": "Family",
         "website": "www.dommuseum.at"
       }
    ]
 }`)